import { Animal } from "@/interface/animal";

export const animal: Array<Animal> = [
  {
    name: "Bear",
    species: "Ursus Arctos",
    age: "20",
    weight: "300",
    habitat: "Forest",
    diet: "Omnivore",
  },
  {
    name: "Chicken",
    species: "Gallus Gallus",
    age: "2",
    weight: "3",
    habitat: "Farm",
    diet: "Omnivore",
  },
  {
    name: "Cow",
    species: "Bos Taurus",
    age: "15",
    weight: "500",
    habitat: "Grassland",
    diet: "Herbivore",
  },
  {
    name: "Crocodile",
    species: "Crocodilia",
    age: "50",
    weight: "500",
    habitat: "Swamp",
    diet: "Carnivore",
  },
  {
    name: "Deer",
    species: "Rusa Unicolor",
    age: "15",
    weight: "150",
    habitat: "Forest",
    diet: "Herbivore",
  },
  {
    name: "Eagle",
    species: "Aquila",
    age: "20",
    weight: "5",
    habitat: "Forest",
    diet: "Carnivore",
  },
  {
    name: "Elephant",
    species: "Loxodonta Africana",
    age: "30",
    weight: "5000",
    habitat: "Forest",
    diet: "Herbivore",
  },
  {
    name: "Falcon",
    species: "Falco",
    age: "10",
    weight: "1.5",
    habitat: "Desert",
    diet: "Carnivore",
  },
  {
    name: "Fox",
    species: "Vulpes Vulpes",
    age: "10",
    weight: "10",
    habitat: "Forest",
    diet: "Carnivore",
  },
  {
    name: "Giraffe",
    species: "Giraffa Camelopardalis",
    age: "20",
    weight: "800",
    habitat: "Savannah",
    diet: "Herbivore",
  },
  {
    name: "Hippopotamus",
    species: "Hippopotamus Amphibius",
    age: "30",
    weight: "1500",
    habitat: "River",
    diet: "Herbivore",
  },
  {
    name: "Horse",
    species: "Equus Caballus",
    age: "20",
    weight: "400",
    habitat: "Grassland",
    diet: "Herbivore",
  },
  {
    name: "Kangaroo",
    species: "Macropus Giganteus",
    age: "25",
    weight: "80",
    habitat: "Grassland",
    diet: "Herbivore",
  },
  {
    name: "Koala",
    species: "Phascolarctos Cinereus",
    age: "15",
    weight: "10",
    habitat: "Eucalyptus Forest",
    diet: "Herbivore",
  },
  {
    name: "Lemur",
    species: "Lemuridae",
    age: "5",
    weight: "4",
    habitat: "Forest",
    diet: "Omnivore",
  },
  {
    name: "Leopard",
    species: "Panthera Pardus",
    age: "12",
    weight: "100",
    habitat: "Savannah",
    diet: "Carnivore",
  },
  {
    name: "Lion",
    species: "Panthera Leo",
    age: "5",
    weight: "250",
    habitat: "Savannah",
    diet: "Carnivore",
  },
  {
    name: "Monkey",
    species: "Macaca Mulatta",
    age: "10",
    weight: "12",
    habitat: "Forest",
    diet: "Omnivore",
  },
  {
    name: "Ostrich",
    species: "Struthio Camelus",
    age: "15",
    weight: "100",
    habitat: "Grassland",
    diet: "Herbivore",
  },
  {
    name: "Parrot",
    species: "Psittacidae",
    age: "10",
    weight: "0.5",
    habitat: "Forest",
    diet: "Omnivore",
  },
  {
    name: "Penguin",
    species: "Spheniscidae",
    age: "8",
    weight: "5",
    habitat: "Antarctica",
    diet: "Carnivore",
  },
  {
    name: "Polar bear",
    species: "Ursus Maritimus",
    age: "20",
    weight: "800",
    habitat: "Arctic",
    diet: "Carnivore",
  },
  {
    name: "Rabbit",
    species: "Leporidae",
    age: "12",
    weight: "5",
    habitat: "Grassland",
    diet: "Herbivore",
  },
  {
    name: "Rattlesnake",
    species: "Vipera",
    age: "20",
    weight: "2",
    habitat: "Desert",
    diet: "Carnivore",
  },
  {
    name: "Snake",
    species: "Serpentes",
    age: "10",
    weight: "1",
    habitat: "Desert",
    diet: "Carnivore",
  },
  {
    name: "Squirrel",
    species: "Sciurus",
    age: "10",
    weight: "0.5",
    habitat: "Forest",
    diet: "Omnivore",
  },
  {
    name: "Tiger",
    species: "Panthera Tigris",
    age: "15",
    weight: "200",
    habitat: "Forest",
    diet: "Carnivore",
  },
  {
    name: "Turtle",
    species: "Testudines",
    age: "50",
    weight: "20",
    habitat: "River",
    diet: "Herbivore",
  },
  {
    name: "Wolf",
    species: "Canis Lupus",
    age: "10",
    weight: "30",
    habitat: "Tundra",
    diet: "Carnivore",
  },
  {
    name: "Zebra",
    species: "Equus Quagga",
    age: "15",
    weight: "400",
    habitat: "Grassland",
    diet: "Herbivore",
  },
];
