import { Animal } from "@/types/Animal";

export const animal: Array<Animal> = [
  {
    name: "Bear",
    species: "Ursus arctos",
    age: 20,
    weight: 300,
    habitat: "Forest",
    diet: "Omnivore",
  },
  {
    name: "Chicken",
    species: "Gallus gallus",
    age: 2,
    weight: 3,
    habitat: "Farm",
    diet: "Omnivore",
  },
  {
    name: "Cow",
    species: "Bos taurus",
    age: 15,
    weight: 500,
    habitat: "Grassland",
    diet: "Herbivore",
  },
  {
    name: "Crocodile",
    species: "Crocodilia",
    age: 50,
    weight: 500,
    habitat: "Swamp",
    diet: "Carnivore",
  },
  {
    name: "Deer",
    species: "Rusa unicolor",
    age: 15,
    weight: 150,
    habitat: "Forest",
    diet: "Herbivore",
  },
  {
    name: "Eagle",
    species: "Aquila",
    age: 20,
    weight: 5,
    habitat: "Forest",
    diet: "Carnivore",
  },
  {
    name: "Elephant",
    species: "Loxodonta africana",
    age: 30,
    weight: 5000,
    habitat: "Forest",
    diet: "Herbivore",
  },
  {
    name: "Falcon",
    species: "Falco",
    age: 10,
    weight: 1.5,
    habitat: "Desert",
    diet: "Carnivore",
  },
  {
    name: "Fox",
    species: "Vulpes vulpes",
    age: 10,
    weight: 10,
    habitat: "Forest",
    diet: "Carnivore",
  },
  {
    name: "Giraffe",
    species: "Giraffa camelopardalis",
    age: 20,
    weight: 800,
    habitat: "Savannah",
    diet: "Herbivore",
  },
  {
    name: "Hippopotamus",
    species: "Hippopotamus amphibius",
    age: 30,
    weight: 1500,
    habitat: "River",
    diet: "Herbivore",
  },
  {
    name: "Horse",
    species: "Equus caballus",
    age: 20,
    weight: 400,
    habitat: "Grassland",
    diet: "Herbivore",
  },
  {
    name: "Kangaroo",
    species: "Macropus giganteus",
    age: 25,
    weight: 80,
    habitat: "Grassland",
    diet: "Herbivore",
  },
  {
    name: "Koala",
    species: "Phascolarctos cinereus",
    age: 15,
    weight: 10,
    habitat: "Eucalyptus forest",
    diet: "Herbivore",
  },
  {
    name: "Lemur",
    species: "Lemuridae",
    age: 5,
    weight: 4,
    habitat: "Forest",
    diet: "Omnivore",
  },
  {
    name: "Leopard",
    species: "Panthera pardus",
    age: 12,
    weight: 100,
    habitat: "Savannah",
    diet: "Carnivore",
  },
  {
    name: "Lion",
    species: "Panthera leo",
    age: 5,
    weight: 250,
    habitat: "Savannah",
    diet: "Carnivore",
  },
  {
    name: "Monkey",
    species: "Macaca mulatta",
    age: 10,
    weight: 12,
    habitat: "Forest",
    diet: "Omnivore",
  },
  {
    name: "Ostrich",
    species: "Struthio camelus",
    age: 15,
    weight: 100,
    habitat: "Grassland",
    diet: "Herbivore",
  },
  {
    name: "Parrot",
    species: "Psittacidae",
    age: 10,
    weight: 0.5,
    habitat: "Forest",
    diet: "Omnivore",
  },
  {
    name: "Penguin",
    species: "Spheniscidae",
    age: 8,
    weight: 5,
    habitat: "Antarctica",
    diet: "Carnivore",
  },
  {
    name: "Polar bear",
    species: "Ursus maritimus",
    age: 20,
    weight: 800,
    habitat: "Arctic",
    diet: "Carnivore",
  },
  {
    name: "Rabbit",
    species: "Leporidae",
    age: 12,
    weight: 5,
    habitat: "Grassland",
    diet: "Herbivore",
  },
  {
    name: "Rattlesnake",
    species: "Vipera",
    age: 20,
    weight: 2,
    habitat: "Desert",
    diet: "Carnivore",
  },
  {
    name: "Snake",
    species: "Serpentes",
    age: 10,
    weight: 1,
    habitat: "Desert",
    diet: "Carnivore",
  },
  {
    name: "Squirrel",
    species: "Sciurus",
    age: 10,
    weight: 0.5,
    habitat: "Forest",
    diet: "Omnivore",
  },
  {
    name: "Tiger",
    species: "Panthera tigris",
    age: 15,
    weight: 200,
    habitat: "Forest",
    diet: "Carnivore",
  },
  {
    name: "Turtle",
    species: "Testudines",
    age: 50,
    weight: 20,
    habitat: "River",
    diet: "Herbivore",
  },
  {
    name: "Wolf",
    species: "Canis lupus",
    age: 10,
    weight: 30,
    habitat: "Tundra",
    diet: "Carnivore",
  },
  {
    name: "Zebra",
    species: "Equus quagga",
    age: 15,
    weight: 400,
    habitat: "Grassland",
    diet: "Herbivore",
  },
];
